imports:
    - { resource: 'providers.yml' }

services:
    payum.stripe_checkout_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [ FluxSE\PayumStripe\StripeCheckoutSessionGatewayFactory ]
        tags:
            - { name: payum.gateway_factory_builder, factory: stripe_checkout }

    payum.stripe_js_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [ FluxSE\PayumStripe\StripeJsGatewayFactory ]
        tags:
            - { name: payum.gateway_factory_builder, factory: stripe_js }

    CoreShop\Payum\StripeBundle\Form\Payment\StripeGatewayConfigurationType:
        tags:
            - { name: form.type }

    CoreShop\Payum\StripeBundle\Form\Payment\StripeCheckoutGatewayConfigurationType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: stripe_checkout }
            - { name: form.type }

    CoreShop\Payum\StripeBundle\Form\Payment\StripeJsGatewayConfigurationType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: stripe_js }
            - { name: form.type }

    CoreShop\Payum\StripeBundle\Action\ConvertPaymentAction:
        public: true
        arguments:
            $detailsProvider: '@coreshop.payum_stripe_checkout.provider.details'
        tags:
            - { name: payum.action, factory: stripe_checkout, alias: coreshop.payum_stripe_checkout.convert_payment }

    CoreShop\Payum\StripeBundle\Extension\UpdatePaymentStateExtension:
        public: true
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManagerInterface'
            - '@coreshop.repository.payment'
            - '@CoreShop\Bundle\PayumBundle\Factory\GetStatusFactoryInterface'
        tags:
            - { name: payum.extension, factory: stripe_checkout, alias: coreshop.payum_stripe_checkout.update_payment_state }